---
- name: nginx restart
  docker_container:
    name: nginx
    restart: yes

- name: restore iptables
  shell: "iptables-restore < /etc/iptables/rules.v4"

- name: apply netplan
  command: netplan apply
  async: 45
  poll: 0
