---
- name: Run node-exporter service
  docker_container:
    name: node-exporter
    image: "{{ registry }}/node-exporter:{{ node_exporter_version }}"
    restart_policy: unless-stopped
    command: --path.rootfs=/host
    network_mode: host
    pid_mode: host
    volumes:
      - /:/host:ro,rslave
  when: "'node' in exporters"

- name: Run nginx-exporter service
  docker_container:
    name: nginx-exporter
    image: "{{ registry }}/nginx-prometheus-exporter:{{ nginx_exporter_version }}"
    restart_policy: unless-stopped
    network_mode: host
    command: -nginx.scrape-uri=http://127.0.0.1:8080/stub_status
  when: "'nginx' in exporters"

- name: Run mysql-exporter service
  docker_container:
    name: mysql-exporter
    image: "{{ registry }}/mysqld-exporter:{{ mysql_exporter_version }}"
    restart_policy: unless-stopped
    network_mode: host
    env:
      DATA_SOURCE_NAME: "{{ phonebook_username }}:{{ phonebook_password }}@(127.0.0.1:3306)/"
  when: "'mysql' in exporters"

- name: Run elasticsearch-exporter service
  docker_container:
    name: es-exporter
    image: "{{ registry }}/elasticsearch-exporter:{{ elasticsearch_exporter_version }}"
    restart_policy: unless-stopped
    network_mode: host
    command: --es.uri=http://127.0.0.1:9200
  when: "'es' in exporters"

- name: Run custom-exporter service
  docker_container:
    name: custom-exporter
    image: "{{ registry }}/cexporter"
    restart_policy: unless-stopped
    network_mode: host
    env:
      REST_API_DEL_URL: https://api.bukhara-chkh.ir/phonebook/user/
      REST_API_ADD_URL: https://api.bukhara-chkh.ir/phonebook/user/
      NGINX_ADDR: https://monitor.bukhara-chkh.ir
      DNS_ADDR: api.bukhara-chkh.ir
      DNS_IP: "{{ nginx_public_ip }}"
      EXTERNAL_ADDR: https://google.com
      GATEWAY_IP: "{{ gateway_private_ip_eth1 }}"

  when: "'custom' in exporters"
