---
- name: Create a data container
  docker_container:
    name: mysql
    image: "{{registry}}/mysql:8.0"
    volumes:
      - /dbdata:/var/lib/mysql"
    env:
      MYSQL_ROOT_USER: "{{root_user}}"
      MYSQL_ROOT_PASSWORD: "{{root_password}}"
    # ports:
    #   - "3306:3306"
    network_mode: "host"
    restart_policy: "unless-stopped"

- name: Waits for mysql to start
  wait_for:
    host: 127.0.0.1
    port: 3306
    delay: 5
